/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author AliRafael
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnVer = new javax.swing.JPanel();
        btVerTextura = new javax.swing.JButton();
        btverMaterial = new javax.swing.JButton();
        btVerPelota = new javax.swing.JButton();
        PnCrear = new javax.swing.JPanel();
        btCrearTextura = new javax.swing.JButton();
        btCrearMaterial = new javax.swing.JButton();
        btCrearPelota = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generador Pelotas");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PnVer.setBackground(new java.awt.Color(48, 85, 175));
        PnVer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(9, 27, 92), 6, true));

        btVerTextura.setBackground(new java.awt.Color(0, 0, 102));
        btVerTextura.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btVerTextura.setForeground(new java.awt.Color(255, 255, 255));
        btVerTextura.setText("Textura");

        btverMaterial.setBackground(new java.awt.Color(0, 0, 102));
        btverMaterial.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btverMaterial.setForeground(new java.awt.Color(255, 255, 255));
        btverMaterial.setText("Material");

        btVerPelota.setBackground(new java.awt.Color(0, 0, 102));
        btVerPelota.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btVerPelota.setForeground(new java.awt.Color(255, 255, 255));
        btVerPelota.setText("Pelotas");

        javax.swing.GroupLayout PnVerLayout = new javax.swing.GroupLayout(PnVer);
        PnVer.setLayout(PnVerLayout);
        PnVerLayout.setHorizontalGroup(
            PnVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnVerLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(PnVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btVerTextura, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btverMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVerPelota, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );
        PnVerLayout.setVerticalGroup(
            PnVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnVerLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btVerPelota, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btverMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btVerTextura, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        getContentPane().add(PnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 270, 370));

        PnCrear.setBackground(new java.awt.Color(138, 198, 146));
        PnCrear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(13, 75, 26), 6, true));

        btCrearTextura.setBackground(new java.awt.Color(4, 77, 15));
        btCrearTextura.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btCrearTextura.setForeground(new java.awt.Color(255, 255, 255));
        btCrearTextura.setText("Textura");

        btCrearMaterial.setBackground(new java.awt.Color(4, 77, 15));
        btCrearMaterial.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btCrearMaterial.setForeground(new java.awt.Color(255, 255, 255));
        btCrearMaterial.setText("Material");

        btCrearPelota.setBackground(new java.awt.Color(4, 77, 15));
        btCrearPelota.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btCrearPelota.setForeground(new java.awt.Color(255, 255, 255));
        btCrearPelota.setText("Pelota");

        javax.swing.GroupLayout PnCrearLayout = new javax.swing.GroupLayout(PnCrear);
        PnCrear.setLayout(PnCrearLayout);
        PnCrearLayout.setHorizontalGroup(
            PnCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnCrearLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(PnCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCrearTextura, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCrearMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCrearPelota, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );
        PnCrearLayout.setVerticalGroup(
            PnCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnCrearLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(btCrearPelota, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btCrearMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btCrearTextura, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        getContentPane().add(PnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 270, 370));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ver");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 100, 40));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crear");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 110, 40));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/BG.jpg"))); // NOI18N
        BG.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 6, true));
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /** 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JPanel PnCrear;
    private javax.swing.JPanel PnVer;
    private javax.swing.JButton btCrearMaterial;
    private javax.swing.JButton btCrearPelota;
    private javax.swing.JButton btCrearTextura;
    private javax.swing.JButton btVerPelota;
    private javax.swing.JButton btVerTextura;
    private javax.swing.JButton btverMaterial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
